service:
  flush: 15
  daemon: 'off'
  log_level: info
  parsers_file: /fluent-bit/etc/parsers.conf

pipeline:
  inputs:
    - name: tail
      path: /media/lucidlink/.lucid_audit/*/*/*/*.log
      parser: audit_json
      db: /fluent-bit/db/logs.db
      read_from_head: true
      path_key: source.filename
      offset_key: source.offset

  filters:
    - name: lua
      match: '*'
      call: parse_time
      time_as_table: true
      code: |
        function parse_time(tag, timestamp, record)
          local recordTimestamp;
          if record["timestamp"] then
            local microseconds = record["timestamp"]
            recordTimestamp = {
              sec = math.floor(microseconds / 1000000),
              nsec = (microseconds % 1000000) * 1000
            }
            record["timestamp"] = nil
            return 1, recordTimestamp, record
          end
          return 0, timestamp, record
        end

  outputs:
    - name: stdout
      match: '*'
    - name: es
      match: '*'
      host: elasticsearch-node1
      port: 9200
      index: audit-trail
      suppress_type_name: on
      buffer_size: 2MB
      replace_dots: on
      logstash_format: off
      retry_limit: 5
      net.keepalive: on
      tls: off
      trace_output: on
      trace_error: on